CREATE OR REPLACE PROCEDURE second_highest_record 
IS
    TYPE order_record IS RECORD (
        ORDER_REFERENCE VARCHAR2(100),
        ORDER_PERIOD VARCHAR2(100),
        SUPPLIER_NAME VARCHAR2(100),
        ORDER_TOTAL_AMOUNT VARCHAR2(100),
        HEADER_ORDER_STATUS VARCHAR2(100),
        INVOICE_REFERENCES VARCHAR2(100)
    );
    rec order_record;
BEGIN
    SELECT 
        ORDER_REFERENCE,
        ORDER_PERIOD,
        SUPPLIER_NAME,
        TO_CHAR(ORDER_TOTAL_AMOUNT, '99,999,990.00'),
        HEADER_ORDER_STATUS,
        INVOICE_REFERENCES
    INTO rec
    FROM (
        SELECT
            REGEXP_REPLACE(SUBSTR(PL.ORDER_LINE_REF, 1, INSTR(PL.ORDER_LINE_REF, '-') - 1), '[^1-9]', '') AS ORDER_REFERENCE,
            TO_CHAR(TO_DATE(M_PH.ORDER_DATE, 'DD-MM-YY'), 'Month DD, YYYY') AS ORDER_PERIOD,
            (SELECT LISTAGG(DISTINCT INVOICE_REF, ',') WITHIN GROUP (ORDER BY INVOICE_REF) 
             FROM MCB_INVOICES 
             WHERE ORDER_HEADER_ID = PL.ORDER_HEADER_ID) AS INVOICE_REFERENCES,
            M_PH.ORDER_TOTAL_AMOUNT,
            (SELECT UPPER(SUPPLIER_NAME) 
             FROM MCB_SUPPLIERS SUP 
             WHERE SUP.SUPPLIER_ID = M_PH.SUPPLIER_ID) AS SUPPLIER_NAME,
            M_PH.ORDER_STATUS AS HEADER_ORDER_STATUS,
            ROW_NUMBER() OVER (ORDER BY M_PH.ORDER_TOTAL_AMOUNT DESC) AS RN
        FROM 
            MCB_ORDER_LINES PL
        JOIN 
            MCB_ORDER_HEADERS M_PH 
        ON 
            PL.ORDER_HEADER_ID = M_PH.ORDER_HEADER_ID
    ) 
    WHERE RN = 2;

    DBMS_OUTPUT.PUT_LINE('Order Reference: ' || rec.ORDER_REFERENCE);
    DBMS_OUTPUT.PUT_LINE('Order Date: ' || rec.ORDER_PERIOD);
    DBMS_OUTPUT.PUT_LINE('Supplier Name: ' || rec.SUPPLIER_NAME);
    DBMS_OUTPUT.PUT_LINE('Order Total Amount: ' || rec.ORDER_TOTAL_AMOUNT);
    DBMS_OUTPUT.PUT_LINE('Order Status: ' || rec.HEADER_ORDER_STATUS);
    DBMS_OUTPUT.PUT_LINE('Invoice References: ' || rec.INVOICE_REFERENCES);

END;
/





EXEC second_highest_record;
