--- Create the schema
CREATE USER MCB IDENTIFIED BY "Password@123";
--- Grant privileges
GRANT CONNECT, RESOURCE TO MCB;
--- I have added some optional privileges
GRANT CREATE SESSION TO MCB;
GRANT CREATE TABLE TO MCB;
GRANT CREATE VIEW TO MCB;
GRANT CREATE PROCEDURE TO MCB;
GRANT CREATE SEQUENCE TO MCB;
GRANT CREATE TRIGGER TO MCB;

--- Granting access to MCB schema on all tables from DEV_USER schema:
BEGIN
    FOR i IN (SELECT table_name FROM all_tables WHERE owner = 'DEV_USER') LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON DEV_USER.' || i.table_name || ' TO MCB';
    END LOOP;
END;/

--- Before data insertion 

ALTER USER MCB QUOTA UNLIMITED ON DATA;


CREATE TABLE MCB_SUPPLIERS (
    Supplier_ID NUMBER GENERATED ALWAYS AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1
    START WITH 1 NOCACHE PRIMARY KEY, 
    Supplier_Name VARCHAR2(250) NOT NULL,
    Supplier_ContactName VARCHAR2(250),
    Supplier_Address VARCHAR2(500),
    Supplier_Contact VARCHAR2(20),
    Supplier_Email VARCHAR2(50),
    CONSTRAINT SUPPLIERS_UNIQUE UNIQUE (Supplier_Name, Supplier_Contact)
);


CREATE TABLE MCB_ORDER_HEADERS (
    ORDER_HEADER_ID NUMBER GENERATED ALWAYS AS IDENTITY 
        MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 
        START WITH 1 NOCACHE PRIMARY KEY,
    ORDER_REF VARCHAR(50) NOT NULL,
    Supplier_ID NUMBER,
    ORDER_DATE DATE,
    ORDER_TOTAL_AMOUNT NUMBER,
    ORDER_STATUS VARCHAR(20),
    CONSTRAINT FK_MCB_ORDER_HEADERS_SupplierID FOREIGN KEY (Supplier_ID) REFERENCES MCB_SUPPLIERS(Supplier_ID)
);



CREATE TABLE MCB_ORDER_LINES (
    ORDER_LineID NUMBER GENERATED ALWAYS AS IDENTITY 
	MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 
	START WITH 1 NOCACHE  PRIMARY KEY,
	ORDER_LINE_REF VARCHAR(50) NOT NULL,
    ORDER_HEADER_ID number,
    ORDER_LINEAMOUNT number,
    ORDER_LINEDESC VARCHAR(255),
    ORDER_LINESTATUS VARCHAR(50),
    CONSTRAINT FK_ORDER_LINES_HEADERID FOREIGN KEY (ORDER_HEADER_ID) 
	REFERENCES MCB_ORDER_HEADERS(ORDER_HEADER_ID)
);

CREATE TABLE MCB_INVOICES (
    Invoice_ID NUMBER GENERATED ALWAYS AS IDENTITY 
	MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 
	START WITH 1 NOCACHE  PRIMARY KEY,
	ORDER_HEADER_ID NUMBER,
    Invoice_Ref VARCHAR(50) ,
	Invoice_Amount number,
    Invoice_Date DATE,
    Invoice_Status VARCHAR(50),
    Invoice_HoldReason VARCHAR(255),
    Invoice_Desc VARCHAR(255),
	CONSTRAINT FK_ORDER_HEADERID FOREIGN KEY (ORDER_HEADER_ID) REFERENCES MCB_ORDER_HEADERS(ORDER_HEADER_ID)

);




