CREATE OR REPLACE PROCEDURE Migrate_Data_TO_mcbTables AS
BEGIN
    -- Insert data into Supplier
    INSERT INTO MCB_SUPPLIERS
	(
		Supplier_Name ,
		Supplier_ContactName ,
		Supplier_Address ,
		Supplier_Contact,
		Supplier_Email
	)
    SELECT distinct 
		SUPPLIER_NAME,
		SUPP_CONTACT_NAME,
		SUPP_ADDRESS,
		SUPP_CONTACT_NUMBER,
		SUPP_EMAIL
    FROM DEV_USER.XXBCM_ORDER_MGT;
    
    -- Insert data into MCB_ORDER_HEADERS
    INSERT INTO MCB_ORDER_HEADERS 
	(
	    ORDER_REF,
		Supplier_ID,
		ORDER_DATE,
	    ORDER_TOTAL_AMOUNT,
		ORDER_STATUS
	)
    SELECT  
	OM.ORDER_REF,
    (SELECT Supplier_ID FROM MCB_SUPPLIERS WHERE Supplier_Name = OM.SUPPLIER_NAME 
     and Supplier_Contact = OM.SUPP_CONTACT_NUMBER ) Supplier_ID,
     OM.ORDER_DATE,
    to_number(replace(OM.ORDER_TOTAL_AMOUNT,',', '')) ORDER_TOTAL_AMOUNT,
	OM.ORDER_STATUS	
    FROM DEV_USER.XXBCM_ORDER_MGT OM 
	where NOT REGEXP_LIKE (OM.ORDER_REF, '[^A-Za-z0-9, ]')
	ORDER BY OM.ORDER_REF ;
	
	-- Insert data into MCB_ORDER_LINES
	
	INSERT INTO MCB_ORDER_LINES
	(
	    ORDER_HEADER_ID,
        ORDER_LINE_REF,
		ORDER_LINEAMOUNT,
		ORDER_LINEDESC,
		ORDER_LINESTATUS
	)
   SELECT  
    (SELECT ORDER_HEADER_ID 
     FROM MCB_ORDER_HEADERS 
     WHERE ORDER_REF = SUBSTR(OM.ORDER_REF, 1, INSTR(OM.ORDER_REF, '-') - 1)
     AND ROWNUM = 1) AS ORDER_HEADER_ID,
     OM.ORDER_REF,
    REGEXP_REPLACE(OM.ORDER_LINE_AMOUNT, '[^0-9]', '') ORDER_LINE_AMOUNT,
    OM.ORDER_DESCRIPTION,
    OM.ORDER_STATUS
FROM DEV_USER.XXBCM_ORDER_MGT OM 
WHERE REGEXP_LIKE (OM.ORDER_REF, '[^A-Za-z0-9]')
ORDER BY OM.ORDER_REF;

	-- Insert data into MCB_INVOICES

INSERT INTO MCB_INVOICES
	(
        Invoice_Ref,
        ORDER_HEADER_ID,
         Invoice_Amount,
        Invoice_Date,
        Invoice_Status,
        Invoice_HoldReason,
        Invoice_Desc
	)
    SELECT  
OM.INVOICE_REFERENCE,
(SELECT ORDER_HEADER_ID 
     FROM MCB_ORDER_HEADERS 
     WHERE ORDER_REF = SUBSTR(OM.ORDER_REF, 1, INSTR(OM.ORDER_REF, '-') - 1)
     AND ROWNUM = 1) AS ORDER_HEADER_ID,
--replace(SUBSTR(INVOICE_REFERENCE, INSTR(INVOICE_REFERENCE, '_') + 1),'.','-') AS INVOICE_REFERENCE,
REGEXP_REPLACE(OM.INVOICE_AMOUNT, '[^0-9]', '') as INVOICE_AMOUNT,
OM.INVOICE_DATE,
OM.INVOICE_STATUS,
OM.INVOICE_HOLD_REASON,
--INVOICE_AMOUNT INVOICE_AMOUNT_,
OM.INVOICE_DESCRIPTION
FROM DEV_USER.XXBCM_ORDER_MGT OM
--where OM.INVOICE_REFERENCE is not null
order by OM.INVOICE_REFERENCE ;

 
    COMMIT;
END;
/
